### ISSUE TITLE
meshgrid error 

### ISSUE THREAD

**Issue by yurenji** [ejmejm/AI-Art-Generation#1]
I was running it on a vastai instance and got the following error. Could u plz take a look? 

```
root@C.2533938:/workspace/AI-Art-Generation$ python gen_cli.py -p low -n 1
Downloading: 100%|█████████████████████████████████████████████████████████████████████████| 665/665 [00:00<00:00, 771kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████| 548M/548M [00:20<00:00, 26.4MB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████| 1.04M/1.04M [00:00<00:00, 1.59MB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████| 456k/456k [00:00<00:00, 862kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████| 1.36M/1.36M [00:00<00:00, 2.09MB/s]
No titles given, so generating a random title...
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Generated titles:
Blues/Pink and Artisan Magic Lantern (Amber Tippet L.E.)
Setting jit to False because torch version is not 1.7.1.
Traceback (most recent call last):
  File "gen_cli.py", line 52, in <module>
    generate_image(text.strip(), preset, True)
  File "/workspace/AI-Art-Generation/image_gen.py", line 89, in generate_image
    save_gif = False
  File "/opt/conda/lib/python3.7/site-packages/deep_daze/deep_daze.py", line 374, in __init__
    averaging_weight=averaging_weight,
  File "/opt/conda/lib/python3.7/site-packages/deep_daze/deep_daze.py", line 172, in __init__
    image_height=image_width
  File "/opt/conda/lib/python3.7/site-packages/siren_pytorch/siren_pytorch.py", line 137, in __init__
    mgrid = torch.stack(torch.meshgrid(*tensors, indexing = 'ij'), dim=-1)
TypeError: meshgrid() got an unexpected keyword argument 'indexing'
```

**Comment by yurenji** [comment]
seems a issue with the pytorch version.
